$NetBSD$

--- wezterm-font/Cargo.toml.orig	2021-05-02 22:42:44.000000000 +0000
+++ wezterm-font/Cargo.toml
@@ -7,7 +7,7 @@ edition = "2018"
 # See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
 
 [dependencies]
-allsorts = { git = "https://github.com/yeslogic/allsorts.git", rev="3947164a201ab5e15d5f23204faaaaaad52531aa" }
+allsorts = "0.5.1"
 anyhow = "1.0"
 config = { path = "../config" }
 enum-display-derive = "0.1"
