$NetBSD$

--- wezterm-ssh/Cargo.toml.orig	2021-05-02 22:42:44.000000000 +0000
+++ wezterm-ssh/Cargo.toml
@@ -19,8 +19,8 @@ log = "0.4"
 portable-pty = { version="0.4", path = "../pty" }
 regex = "1"
 smol = "1.2"
-ssh2 = {version="0.9", features=["openssl-on-win32"]}
-#ssh2 = {version="0.9"}
+#ssh2 = {version="0.9", features=["openssl-on-win32"]}
+ssh2 = {version="0.9"}
 
 [dev-dependencies]
 k9 = "0.11.0"
