$NetBSD$

--- Cargo.toml.orig	2021-05-02 22:42:44.000000000 +0000
+++ Cargo.toml
@@ -15,6 +15,3 @@ opt-level = 3
 [profile.dev]
 # https://jakedeichert.com/blog/reducing-rust-incremental-compilation-times-on-macos-by-70-percent/
 split-debuginfo = "unpacked"
-
-[patch.crates-io]
-ssh2 = { git = "https://github.com/wez/ssh2-rs.git", branch="win32ssl" }
