$NetBSD$

--- window/Cargo.toml.orig	2021-05-02 22:42:44.000000000 +0000
+++ window/Cargo.toml
@@ -56,7 +56,7 @@ filedescriptor = { version="0.7", path =
 x11 = {version ="2.18", features = ["xlib_xcb"]}
 xcb = {version="0.9", features=["render", "xkb", "xlib_xcb"]}
 xcb-util = { features = [ "cursor", "image", "icccm", "ewmh", "keysyms"], version = "0.3" }
-xkbcommon = { version = "0.5", features = ["x11", "wayland"], git="https://github.com/wez/xkbcommon-rs.git", rev="01a0a0cd5663405e6e4abb1ad3add9add1496f58"}
+xkbcommon = { version = "0.4.0", features = ["x11", "wayland"] }
 mio = "0.6"
 libc = "0.2"
 #smithay-client-toolkit = {version = "0.9", optional = true, features=["calloop"], git="https://github.com/wez/client-toolkit.git", branch="title_trunc"}
